config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :stadia do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy]

  get "dashboard", to: "pages#dashboard"
  get "profile", to: "pages#profile"
  get "settings", to: "pages#settings"
  get "bookings", to: "bookings#index"
  patch "settings", to: "pages#update"
  get "contact", to: "pages#contact"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :stadium

  validates :start_date, :end_date, presence: true
  validates :stadium, presence: true
  validates :user, presence: true
  validate :start_date_after_now
  validate :end_date_after_start_date
  validate :stadium_available

  private

  def start_date_after_now
    return if start_date.blank?

    if start_date < Date.today
      errors.add(:start_date, "Start date must be after today")
    end
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "End date must be after the start date")
    end
  end

  def stadium_available
    return if start_date.blank? || end_date.blank? || stadium.blank?

    if stadium.bookings.where("start_date <= ? AND end_date >= ?", end_date, start_date).any?
      errors.add(:stadium, "This stadium is not available in this period")
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stadium
  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, presence: true, inclusion: { in: 1..5 }
end

app/models/stadium.rb
class Stadium < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy
  has_many_attached :pictures
  has_one_attached :photo

  validates :name, presence: true
  validates :location, presence: true
  validates :stadium_description, presence: true, length: { minimum: 100 }
  validates :price, presence: true
  validates :user, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_description_and_location, against: [ :stadium_description, :location ], using: {
    tsearch: { prefix: true }
  }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stadiums, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :picture

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :user_description, :picture, :email, :password, :password_confirmation, :current_password)}
    # For additional in app/views/devise/registrations/edit.html.erb
    #devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_description, :picture]

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :user_description, :picture, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  def show
    @review = Review.new
  end

  def new
    @booking = Booking.new
    @stadium = Stadium.find(params[:stadium_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.stadium = Stadium.find(params[:stadium_id])
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :stadium_id, :user_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact, :start]

  def home
  end

  def dashboard
    @bookings = current_user.bookings
    @stadia = current_user.stadiums
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def booking
    @booking = Booking.find(params[:id])
  end

  def settings
    @user = current_user
  end

  def contact
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_stadium, only: %i[new create]

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.stadium = @stadium
    if @review.save
      redirect_to stadium_path(@stadium)
    else
      render 'stadia/show', status: :unprocessable_entity
    end
  end

  private

  def set_stadium
    @stadium = Stadium.find(params[:stadium_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController
  before_action :set_stadium, only: [:show, :edit, :update, :destroy]

  def index

    if params[:search].present?
      @stadia = Stadium.search_by_description_and_location(params[:search])
      @reviews = Review.all
      @rating = @reviews.average(:rating)
      set_markers
    else
      @stadia = Stadium.all
      set_markers
    end
  end

  def show
    @stadium = Stadium.find(params[:id])
    @review = Review.new
    @markers = [{
      lat: @stadium.latitude,
      lng: @stadium.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {stadium: @stadium}),
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def new
    @stadium = Stadium.new
  end

  def create
    @stadium = Stadium.new(stadium_params)
    @stadium.user = current_user
    if @stadium.save
      redirect_to stadia_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @stadium.update(stadium_params)
    redirect_to stadium_path(@stadium)
  end

  def destroy
    @stadium.destroy
    redirect_to stadia_path(@stadium), status: :see_other
  end

  private

  def stadium_params
    params.require(:stadium).permit(:name, :location, :capacity, :stadium_description, :energy_class, :price, :photo, pictures: [])
  end

  def set_stadium
    @stadium = Stadium.find(params[:id])
  end

  def set_markers
    @markers = @stadia.geocoded.map do |stadium|
    {
      lat: stadium.latitude,
      lng: stadium.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {stadium: stadium}),
      marker_html: render_to_string(partial: "marker")
    }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div id='stadium-booking-dates' data-unavailable="<%= @stadium.unavailable_dates.to_json %>">
  <%= simple_form_for [@stadium, @booking], data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :start_date, as: :string, placeholder: "Start date", input_html: { data: { flatpickr_target: "startTime" } } %>
    <%= f.input :end_date, as: :string, placeholder: "End date", input_html: { data: { flatpickr_target: "endTime" } } %>
    <%= f.submit 'Schedule your appointment' %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div>
  <h1>All my bookings</h1>
</div>
</br>
<div>
  <h2>Bookings to come</h2>
</div>

<div class="container-bookings">
  <% @bookings.each do |booking| %>
    <div class="booking-card-details">
      <%if booking.start_date >= Date.today %>
        <%# <div class="booking-details"> %>
          <p>Name: <%= booking.stadium.name %></p>
          <p>Start date: <%= booking.start_date %></p>
          <p><%= booking.end_date %></p>
          <p><%= link_to "View details", booking_path(booking) %></p>
        <%# </div> %>
      <% end %>
    </div>
  <% end %>
</div>

<div>
  <h2>Past bookings</h2>
</div>

<div class="container-bookings">
  <% @bookings.each do |booking| %>
    <div class="booking-card-details">
      <%if booking.start_date < Date.today %>
        <%# <div class="booking-details"> %>
          <p>Name: <%= booking.stadium.name %></p>
          <p>Start date: <%= booking.start_date %></p>
          <p><%= booking.end_date %></p>
          <p><%= link_to "View details", booking_path(booking) %></p>
        <%# </div> %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container-booking">
  <h1>Book stadium</h1>

  <div class="booking-box col-md-4">
  <div class="listing-price">
    <h4><%= @stadium.price %> $</h4>
    <p> per day (service fees included)</p><br>
  </div>

  <div class="booking-form">
    <h4>Book your appointment</h4>
    <p>Choose your date and time</p>

  <%= render 'form' %>

  <%= link_to "Back to Stadium", stadium_path(@stadium), class: "btn btn-primary" %>
  <%= link_to "Back to Stadiums list", stadia_path(@stadium), class: "btn btn-primary" %>

</div>

app/views/bookings/show.html.erb
<div class="container-booking-details">
  <h2>Congratulations, you've just booked the <%= @booking.stadium.name %></h2>
  </br>
  <h3>Here are your booking details</h3>

  <div class="booking-dates-details">
    <p><strong>Start Date:</strong> <%= @booking.start_date %></p>
    <p><strong>End Date:</strong> <%= @booking.end_date %></p>
    <% length = (@booking.end_date - @booking.start_date).to_i %>
    <p><strong>Booking days:</strong> <%= length %> days</p>
  </div>

  <div class="booking-details">
    <p><strong>Stadium:</strong> <%= @booking.stadium.name %></p>
    <p><strong>Location:</strong> <%= @booking.stadium.location %></p>
    <p><strong>Capacity:</strong> <%= @booking.stadium.capacity %></p>
    <p><strong>Energy Class:</strong> <%= @booking.stadium.energy_class %></p>
    <p><strong>Price:</strong> <%= @booking.stadium.price %> $</p>
  </div>

  <div class="booking-total-details">
    <p><strong> Total Price: <%= @booking.stadium.price * length %> $</p>
  </div>

  <%# <%= simple_form_for [@booking, @review] do |f| %>
    <%# <%= f.input :content, label: "Leave a review for this stadium" %>
    <%# <%= f.input :rating, label: "Leave your rating for this stadium" %>
    <%# <%= f.submit "Submit", class: "btn btn-primary" %>
  <%# <% end %>

    <div class="booking-buttons-details">
      <%= link_to "Back to Stadiums list", stadia_path, class: "btn btn-primary" %>
      <%= link_to "Back to My Bookings", bookings_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css' rel='stylesheet' />

    <title>STADIUMBNB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js" integrity="sha512-f8mwTB+Bs8a5c46DEm7HQLcJuHMBaH/UFlcgyetMqqkvTcYg4g5VXsYR71b3qC82lZytjNYvBj2pf0VekA9/FQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  </head>

  <body class="body_application">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/booking.htlm.erb
 <div class="stadium-card">
 <h1>ma réservation</h1>

<ul>
  <li>
    <%= booking.stadium.name %>
  </li>
  <li>
    <%= @booking.start_date %>
  </li>
  <li>
    <%= @booking.end_date %>
  </li>
  <li>
    <strong><%= booking.total_price %></strong> €
  </li>
</ul>

<%= link_to "retourner à mes réservation", dashboard_path, class: "btn btn-outline-primary" %>
</div>

app/views/pages/contact.html.erb
<div class="container-contact">
  <div class="card-contact card0">
    <div class="border-contact">
      <h2>Alex CTO</h2>
    </div>
  </div>
  <div class="card-contact card1">
    <div class="border-contact">
      <h2>Fred Intern</h2>
    </div>
  </div>
  <div class="card-contact card2">
    <div class="border-contact">
      <h2>Romain CEO</h2>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
 <div class="stadium-card">
<h1>Mon dashboard</h1>
<% if @bookings.empty?  %>
  <p>Vous n'avez pas encore de réservation</p>
<%else%>
  <p>Vous avez <%= @bookings.count %> réservation(s)</p>

<div>
  <h1>All my bookings</h1>
</div>

<div>
  <h2>Bookings to come</h2>
</div>

<div>
  <ul>
    <% @bookings.each do |booking| %>
      <%if booking.start_date >= Date.today %>
        <ul class="stadium-card">
          <p>Name: <%= booking.stadium.name %></p>
          <p>Start date: <%= booking.start_date %></p>
          <p><%= booking.end_date %></p>
          <p><%= link_to "View details", booking_path(booking), class: "btn btn-outline-primary" %></p>
        </ul>
      <% end %>
    <% end %>
  </ul>
</div>


<div>
  <h2>Past bookings</h2>
</div>

<div>
  <ul>
    <% @bookings.each do |booking| %>
      <%if booking.start_date < Date.today %>
        <ul class="stadium-card">
          <p>Name: <%= booking.stadium.name %></p>
          <p>Start date: <%= booking.start_date %></p>
          <p><%= booking.end_date %></p>
        </ul>
      <% end %>
    <% end %>
    <div><%= link_to "retourner à mon profile", profile_path, class: "btn btn-outline-primary" %></h3></div>
  </ul>


  <%end%>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(https://tourismmedia.italia.it/is/image/mitur/20220427155442-tifosi-allo-stadio-milano-lombardiashutterstock-96072692-1?wid=850&hei=500&fit=constrain,1&fmt=webp) ">
  <div class="banner-content text-center">
    <h1>Dreams become true</h1>
    <p class="opacity-75">Find the best stadium for your event</p>
    <%= link_to "Stadiums available", stadia_path, class: "btn btn-lg btn-primary"  %>
  </div>
</div>

<div class="footer p-4">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h3>StadiumBnb</h3>
        <p>StadiumBnb is the best platform to rent a stadium all around the world.</p>
      </div>
      <div class="col-md-4">
        <h3>Links</h3>
        <ul class="list-unstyled">
          <li><%= link_to "Stadiums", stadia_path %></li>
          <li><%= link_to "Add a stadium", new_stadium_path %></li>
          <li><%= link_to "THE Team", contact_path %></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h3>Newsletter</h3>
        <p>Get some news of us each time with add new stuffs for you.</p>
        <form action="#" method="post">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button">Follow us</button>
            </span>
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="text-center">© 2023 StadiumBnb. All rights reserved.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
 <div class="stadium-card">

 <h1> my profile page</h1>



<%= link_to "Mes réservations", dashboard_path, class: "btn btn-outline-primary"  %>

<%= link_to "Editer mes données de profil", edit_user_registration_path, class: "btn btn-outline-primary"  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">

    <div class="d-flex justify-content-center">
      <%= link_to stadia_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/di7k88pkv/image/upload/v1674508155/vtdbsujwjposx3eouhhr.png" %>
      <% end %>
      <h2><strong>Stadium</strong></h2>
      <h5><strong>BnB</strong></h5>
    </div>

    <div><strong><%= link_to "Germany", stadia_path(search:"Germany"), class:"country" %></strong></div>
    <div><strong><%= link_to "France", stadia_path(search:"France"), class:"country" %></strong></div>
    <div><strong><%= link_to "Spain", stadia_path(search:"Spain"), class:"country" %></strong></div>
    <div><strong><%= link_to "Australia", stadia_path(search:"Australia"), class:"country" %></strong></div>
    <div><strong><%= link_to "United States", stadia_path(search:"USA"), class:"country" %></strong></div>
    <div><strong><%= link_to "Italy", stadia_path(search:"Italy"), class:"country" %></strong></div>
    <div><strong><%= link_to "Qatar", stadia_path(search:"Qatar"), class:"country" %></strong></div>
    <div><%= link_to "My bookings", bookings_path, class: "nav-link" %></div>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%=current_user.first_name%> <%=  current_user.last_name %>
            <%= image_tag "https://res.cloudinary.com/di7k88pkv/image/upload/v1674220835/rwcaekxsosig45kistar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Setting", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchingform.html.erb
<%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :name, input_html: {value: ""} %>
  <%= f.input :location, input_html: {value: ""} %>
  <%= f.input :capacity, input_html: {value: ""} %>
  <%= f.input :energy_class, input_html: {value: ""} %>
  <%= f.input :price, input_html: {value: ""} %>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

app/views/stadia/_info_window.html.erb
<div class="window">
<h4><%= stadium.name %></h4>
<p><%= stadium.location %></p>
<%= link_to "See details", stadium_path(stadium), class: "btn btn-primary" %>
</div>

app/views/stadia/_marker.html.erb
<%= image_tag "stadiums/logo.png", height: 20, width: 35, alt: "Logo" %>

app/views/stadia/edit.html.erb
<div class="container-form">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1>Edit stadium</h1>
      <%= simple_form_for @stadium do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :capacity %>
      <%= f.input :energy_class %>
      <%= f.input :price %>
      <%= f.input :stadium_description %>
      <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
      <br><br>
      <%= link_to "Back to Stadiums list", stadia_path, class: "btn btn-primary" %> <br><br>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/stadia/index.html.erb
<div class="container">

  <div class="d-flex justify-content-between">
    <%= simple_form_for :search, method: :get, defaults: { required: false } do |f| %>
      <%= f.input :"", label: "", placeholder: "Search my stadium !", input_html: { name: 'search', value: params.dig(:search) } %>
    <% end %>
    <h6>Book the stadium of your dream !</h6>
    <div class="btn">
      <%= link_to "Register my stadium !", new_stadium_path, class: "btn btn-outline-light" %>
    </div>
  </div>

  <div class="main-container">
    <div class="cards">
      <% @stadia.each do |stadium| %>

        <div class="stadium-card">
          <div class="d-flex justify-content-end">
            <% unless stadium.reviews.blank? %>
              <% starfull = stadium.reviews.sum(:rating)/ stadium.reviews.count %>
              <% starfull.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
              <% (5-starfull).times do %>
                <i class="fa-regular fa-star"></i>
              <% end %>
            <% end %>
          </div>

          <div class="trophy">
            <% if stadium.energy_class == "A+++" %>
              <span><i class="fa-sharp fa-solid fa-trophy"></i> Stadium of the year 2023 <i class="fa-sharp fa-solid fa-trophy"></i></span>
            <% end %>
          </div>

          <h3><%=stadium.name%></h3>
          <div class="pictures_stadium">
            <% stadium.pictures.each do |picture| %>
              <%= cl_image_tag picture.key, height: 250, width: 350, crop: :fill %>
            <% end %><br><br>
          </div>

          <div class="d-flex justify-content-around">
            <div class="left">
              <p>Location : <strong><%=stadium.location%></strong><br>Capacity : <strong><%=stadium.capacity%></strong></p>
            </div>
            <div class="right">
              <p>Energy Class : <strong><%=stadium.energy_class%></strong><br>Price : <strong><%=stadium.price%> $</strong> / day</p>
            </div>
          </div>

          <div class="d-flex justify-content-around">
            <%= link_to "More informations", stadium_path(stadium), class: "btn btn-outline-primary" %>
          </div>

        </div>
      <% end %>
    </div>

    <div id="map" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  </div>
</div>

app/views/stadia/new.html.erb
<div class="container-form">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1>New stadium</h1>
      <%= @error %>
      <%= simple_form_for @stadium do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :capacity %>
      <%= f.input :energy_class %>
      <%= f.input :price %>
      <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
      <%= f.input :stadium_description %>
      <%= f.submit "Create", :confirm => 'Are your sure you want to book this stadium?', class: "btn btn-primary" %>
      <% end %>
      <br>
      <br>
      <%= link_to "Back to Stadiums list", stadia_path, class: "btn btn-primary" %>
      <br>
      <br>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/stadia/show.html.erb
<div class="container">

  <h1><strong><%= @stadium.name %></strong></h1>
  <div class="city"><strong><%= @stadium.location %></strong></div><br>

  <div class="d-flex justify-content-between">

    <div class="main-container">
      <div>
        <div>

          <div class="description">
            <% unless @stadium.reviews.blank? %>
              <% starfull = @stadium.reviews.sum(:rating)/ @stadium.reviews.count %>
              <% starfull.times do %>
                <i class="fa-solid fa-star"></i>
              <% end %>
              <% (5-starfull).times do %>
                <i class="fa-regular fa-star"></i>
              <% end %>
            <% end %><br><br>

          <%= @stadium.stadium_description %></div><br>

          <div class="description-details">
            <div>Capicity : <%= @stadium.capacity %> persons</div>
            <div><%= @stadium.price %> $<strong> / day</strong></div><br>
            <div class="d-flex justify-content-center"><%= link_to "Book this stadium !", new_stadium_booking_path(@stadium),class: "btn btn-outline-light" %></div><br><br><br><br>
          </div>

          <div class="d-flex justify-content-evenly">
            <div class="d-flex" style="width: 40% ; height: 190px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
            <div>
              <% if @stadium.photo.key? %>
                <%= cl_image_tag @stadium.photo.key, height: 190, width: 280, crop: :fill %></div>
              <% else %>
                <img style="height:190px; width:280px;"src="https://res.cloudinary.com/di7k88pkv/image/upload/v1674915880/doxbpq4cehvl4gqzn6rg.png" alt="">
              <% end %>
            </div>
        </div>
      </div>

      <div class="stadium_pictures">
        <% @stadium.pictures.each do |picture| %>
          <%= cl_image_tag picture.key, height: 300, width: 500, crop: :fill %> <br><br>
        <% end %>
      </div>

    </div>

  </div>

    <div class="second-container">

      <h3><%= pluralize @stadium.reviews.size, "review" %><span> for </span><%= @stadium.name %> </h3>
      <h4>  Rate :
      <% if @stadium.reviews.blank? %>
          <i> -- </i></h4><br><br>
        <% else %>
          <%= @stadium.reviews.average(:rating).round(1) %><span>/5</span></h4><br>
        <% end %>

      <% if @stadium.reviews.blank? %>
        <p>Be the first to leave a review for <%= @stadium.name %></p>
      <% else %>
        <% @stadium.reviews.each do |review| %>
          <%= review.rating %>
          <span>/ 5  -   </span>
          <%= review.content %><br>
        <% end %>
      <% end %><br>

      <%= simple_form_for([@stadium, @review]) do |f| %>
      <%= f.input :content, placeholder: "Leave your comment" %>
      <%= f.input :rating, placeholder: "Leave a rate between 1 and 5" %>
      <%= f.button :submit, class: "btn btn-outline-light" %><br><br>
      <% end %>

      </div>
    </div>

  <div class="links">
    <div class="d-flex justify-content-evenly">
      <%= link_to "Back to Stadiums list", stadia_path, class: "btn btn-primary" %>
      <%if current_user.id == @stadium.user_id  %>
        <%= link_to "Edit my stadium", edit_stadium_path(@stadium), class: "btn btn-primary" %>
        <%= link_to "Delete my stadium", stadium_path(@stadium), class: "btn btn-primary", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      <%end %>
    </div>
  </div>
</div>